from turtle import*
import random
l=["man.er","ch.en", "he.lo"]
lien=["c.rdo,ner","sou.fr,nt"]
mdr=0
ger=0
while True:
    print("choisire le niveau")
    g=input()
    if(g=="niveaux"):
        clear()
        if(mdr==len(l)):
            print("vous avez atteint le max")
            mot=input("ajouter mon:")
            l.append(mot)
            lettre=input("ajouter lettre:")
        print(l[mdr])
        x=["g","i","l"]
        a=input()
        if(a==x[mdr]):
            pere=list(l[mdr])
            for i in range(0,len(pere)):
                if(pere[i]=="."):
                    pere[i]=x[mdr]
                    print(pere)
            print("bravo, vous avez gagenr")
            mdr=mdr+1
        else:
            left(90)
            forward(50)
            left(-90)
            forward(100)
            left(-90)
            forward(50)
            forward(-50)
            left(90)
            forward(-50)
            print("recommancer")
            print(l[mdr])
            x=["g","i","l"]
            a=input()
            if(a==x[mdr]):
                pere=list(l[mdr])
                for i in range(0,len(pere)):
                    if(pere[i]=="."):
                        pere[i]=x[mdr]
                        print(pere)
                print("bravaux")
                mdr=mdr+1
            else:
                left(90)
                forward(200)
                left(-90)
                forward(100)
                while True:
                    print("erreur")
                    print("vous avez perdu")
    if(g=="niveaux 2"):
        clear()
        print(lien[ger])
        m=["o","f"]
        p=["n","e"]
        t=input()
        if(t==m[ger]):
            op=list(lien[ger])
            for i in range(0,len(op)):
                if(op[i]=="."):
                    op[i]=m[ger]
                    print(op)
            t=input()
            p=["n","e"]
            m=["o","f"]
            if(t==p[ger]):
                for i in range(0,len(op)):
                    if(op[i]==","):
                        op[i]=p[ger]
                        print(op)   
                print("vous avez gagner")
                ger=ger+1
            else:
                forward(50)
                left(-90)
                forward(50)
                forward(-50)
                left(-90)
                forward(100)
                left(90)
                forward(50)
                forward(-50)
                left(90)
                forward(50)
                print("une faute")
                print("recommancer")
                print("2")
                t=input()
                if(t==p[ger]):
                    for i in range(0,len(op)):
                        if(op[i]==","):
                            op[i]=p[ger]
                            print(op)              
                    print("vous avez gagner avec une faute")
                    ger=ger+1
                else:
                    print("perdu")
                    left(90)
                    forward(200)
                    left(-90)
                    forward(100)
                    up()
                    forward(-100)
                    left(90)
                    forward(-200)
                    left(-90)
                    down()
        else:
            forward(50)
            left(-90)
            forward(50)
            forward(-50)
            left(-90)
            forward(100)
            left(90)
            forward(50)
            forward(-50)
            left(90)
            forward(50)
            print("une faute")
            print("recommancer")
            print("1")
            print(lien[ger])
            m="o"
            p="n"
            t=input()
            if(t==m[ger]):
                op=list(lien[ger])
                for i in range(0,len(op)):
                    if(op[i]=="."):
                        op[i]=m[ger]
                        print(op)
                t=input()
                p="n"
                m="o"
                if(t==p[ger]):
                    for i in range(0,len(op)):
                        if(op[i]==","):
                            op[i]=p[ger]
                            print(op)
                    print("gagner")
                    ger=ger+1
                    
            else:
                print("perdu")
                left(90)
                forward(200)
                left(-90)
                forward(100)
                up()
                forward(-100)
                left(90)
                forward(-200)
                left(-90)
                down()
    if(g=="niveaux 3"):
        print("Rh...d...d...nd...on")
        print(1)
        y=input()
        n1="o"
        if(y==n1):
            print("Rh",n1,"d...d...nd...on")
            print(2)
            n2="o"
            y=input()
            if(y==n2):
                print("Rh",n1,"d",n2,"d...nd...on")
                print(3)
                n3="e"
                y=input()
                if(y==n3):
                    print("Rh",n1,"d",n2,"d",n3,"nd...on")
                    print(4)
                    n4="r"
                    y=input()
                    if(y=="r"):
                        print("Rh",n1,"d",n2,"d",n3,"nd",n4,"on")
                        print("vous avez gagner")
                    else:
                        left(90)
                        forward(50)
                        left(-90)
                        forward(100)
                        left(-90)
                        forward(50)
                        forward(-50)
                        left(90)
                        forward(-50)
                        left(90)
                        forward(200)
                        left(-90)
                        forward(100)
                        up()
                        forward(-100)
                        left(90)
                        forward(-200)
                        left(-90)
                        down()
                        forward(50)
                        left(-90)
                        forward(50)
                        forward(-50)
                        left(-90)
                        forward(100)
                        left(90)
                        forward(50)
                        forward(-50)
                        left(90)
                        forward(50)            
                        print("perdu")                         
                else:
                    left(90)
                    forward(50)
                    left(-90)
                    forward(100)
                    left(-90)
                    forward(50)
                    forward(-50)
                    left(90)
                    forward(-50)
                    left(90)
                    forward(200)
                    left(-90)
                    forward(100)
                    up()
                    forward(-100)
                    left(90)
                    forward(-200)
                    left(-90)
                    down()
                    forward(50)
                    left(-90)
                    forward(50)
                    forward(-50)
                    left(-90)
                    forward(100)
                    left(90)
                    forward(50)
                    forward(-50)
                    left(90)
                    forward(50)            
                    print("perdu")                       
            else:
                left(90)
                forward(50)
                left(-90)
                forward(100)
                left(-90)
                forward(50)
                forward(-50)
                left(90)
                forward(-50)
                left(90)
                forward(200)
                left(-90)
                forward(100)
                up()
                forward(-100)
                left(90)
                forward(-200)
                left(-90)
                down()
                forward(50)
                left(-90)
                forward(50)
                forward(-50)
                left(-90)
                forward(100)
                left(90)
                forward(50)
                forward(-50)
                left(90)
                forward(50)            
                print("perdu")                
        else:
            left(90)
            forward(50)
            left(-90)
            forward(100)
            left(-90)
            forward(50)
            forward(-50)
            left(90)
            forward(-50)
            left(90)
            forward(200)
            left(-90)
            forward(100)
            up()
            forward(-100)
            left(90)
            forward(-200)
            left(-90)
            down()
            forward(50)
            left(-90)
            forward(50)
            forward(-50)
            left(-90)
            forward(100)
            left(90)
            forward(50)
            forward(-50)
            left(90)
            forward(50)            
            print("perdu")         
    print("voulez vous jouer")
    quitter=input()
    if(quitter=="non"):
        break
    elif(quitter=="oui"):
        print("ok")